sdk_test_server:
    image: sdk_test_server
    environment:
      - MBED_CLOUD_SDK_HOST
      - MBED_CLOUD_SDK_API_KEY
    volumes:
      - ./integration-results/coverage:/testserver/coverage
      - ./integration-results/reports:/testserver/reports
      - ./test_fixtures:/testserver/test_fixtures
testrunner:
    image: test_runner_new
    environment:
      - TEST_SERVER_URL=http://sdk_test_server:5000
      #folder on test server to get test files from
      - TEST_FIXTURES_DIR=/testserver/test_fixtures
      - MBED_CLOUD_SDK_HOST
      - MBED_CLOUD_SDK_API_KEY
      - TEST_RUNNER_SHUTDOWN_SERVER=yes
    links:
      - sdk_test_server
    volumes:
      - ./integration-results/results:/runner/results
      - ./test_fixtures:/runner/test_fixtures