version: '2'
services:
    redis:
        image: "redis:alpine"
        container_name: redis
    sdk_test_server:
        container_name: sdk
        build: .
        environment:
          - MBED_CLOUD_HOST=https://lab-api.mbedcloudintegration.net
          - MBED_CLOUD_API_KEY=ak_1MDE1NzUyOGJiODQxMDI0MjBhMDEzMjE0MDAwMDAwMDA01618f8aa7000a580a01017600000000MBLSAiaNHJ9ViZPv5zDM2R4xMffYBDLU
        volumes:
          - ./results:/testserver/build_logs/
          - ./build/coverage-results:/testserver/build/coverage-results
          - ./test_fixtures:/testserver/test_fixtures
    testrunner:
        container_name: testrunner
        command: python -m pytest trunner/modules/update/test_manifest.py
        #build: tests/mbed-cloud-sdk-testrunner
        image: testrunner_image
        environment:
          - TEST_SERVER_URL=http://sdk_test_server:5000
          #folder on test server to get test files from
          - TEST_FIXTURES_DIR=/testserver/test_fixtures
        links:
          - sdk_test_server
          - redis
        volumes:
          - ./results:/runner/results
          - ./test_fixtures:/runner/test_fixtures
